/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';

declare const self: ServiceWorkerGlobalScope;

// ===== MARKER: push-support-v4 =====
// This marker confirms that the custom SW code is deployed
console.log('[SW] push-support-v4 loaded at', new Date().toISOString());

// Precache all assets generated by vite-plugin-pwa
// On some Safari/iOS setups (or if a stale SW is served), __WB_MANIFEST may be missing.
// Workbox will throw at evaluation time which prevents SW registration entirely.
// Fallback to an empty manifest so push can still work.
const wbManifest = (self as unknown as { __WB_MANIFEST?: unknown }).__WB_MANIFEST;
precacheAndRoute(Array.isArray(wbManifest) ? (wbManifest as any) : []);

// Clean up old caches
cleanupOutdatedCaches();

// ============= PUSH NOTIFICATIONS =============
self.addEventListener('push', (event) => {
  console.log('[SW] Push received at:', new Date().toISOString(), 'data:', event.data?.text()?.substring(0, 100));
  
  let data = {
    title: "O'KEY ENGLISH",
    body: 'Новое уведомление',
    icon: '/pwa-192x192.png',
    badge: '/pwa-192x192.png',
    tag: 'default',
    data: {} as Record<string, unknown>
  };

  try {
    if (event.data) {
      const payload = event.data.json();
      data = { ...data, ...payload };
    }
  } catch (e) {
    console.error('[SW] Error parsing push data:', e);
    // Try as text
    if (event.data) {
      data.body = event.data.text();
    }
  }

  const options = {
    body: data.body,
    icon: data.icon || '/pwa-192x192.png',
    badge: data.badge || '/pwa-192x192.png',
    tag: data.tag || 'okey-notification',
    vibrate: [100, 50, 100],
    data: {
      ...data.data,
      url: (data as Record<string, unknown>).url || (data.data as Record<string, unknown>)?.url || '/',
      dateOfArrival: Date.now(),
    },
    actions: [
      { action: 'open', title: 'Открыть' },
      { action: 'close', title: 'Закрыть' }
    ],
    requireInteraction: (data as Record<string, unknown>).requireInteraction as boolean || false,
  };

  event.waitUntil(
    self.registration.showNotification(data.title, options)
  );
});

// ============= NOTIFICATION CLICK =============
self.addEventListener('notificationclick', (event) => {
  console.log('[SW] Notification clicked:', event.action);
  
  event.notification.close();

  if (event.action === 'close') {
    return;
  }

  const urlToOpen = (event.notification.data?.url as string) || '/';

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      // Check if there's already a window open
      for (const client of clientList) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          client.focus();
          if (urlToOpen !== '/') {
            (client as WindowClient).navigate(urlToOpen);
          }
          return;
        }
      }
      // Open new window
      return self.clients.openWindow(urlToOpen);
    })
  );
});

// ============= NOTIFICATION CLOSE =============
self.addEventListener('notificationclose', () => {
  console.log('[SW] Notification closed');
});

// ============= MESSAGE HANDLER =============
self.addEventListener('message', (event) => {
  console.log('[SW] Message received:', event.data);
  
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// ============= ACTIVATE =============
self.addEventListener('activate', (event) => {
  console.log('[SW] Activating service worker with push support');
  event.waitUntil(self.clients.claim());
});
