/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches, PrecacheEntry } from 'workbox-precaching';

declare const self: ServiceWorkerGlobalScope;

// ===== MARKER: push-support-v5 =====
// This marker confirms that the custom SW code is deployed
console.log('[SW] push-support-v5 loaded at', new Date().toISOString());

// Force immediate activation - critical for iOS PWA updates
self.addEventListener('install', () => {
  console.log('[SW] Installing, calling skipWaiting()');
  self.skipWaiting();
});

// Type for Workbox manifest entries
type ManifestEntry = PrecacheEntry | string;

// Precache all assets generated by vite-plugin-pwa
// On some Safari/iOS setups (or if a stale SW is served), __WB_MANIFEST may be missing.
// Workbox will throw at evaluation time which prevents SW registration entirely.
// Fallback to an empty manifest so push can still work.
const wbManifest = (self as unknown as { __WB_MANIFEST?: ManifestEntry[] }).__WB_MANIFEST;
precacheAndRoute(Array.isArray(wbManifest) ? wbManifest : []);

// Clean up old caches
cleanupOutdatedCaches();

// ============= PUSH NOTIFICATIONS =============

// Types for push notification data
interface PushNotificationData {
  title?: string;
  body?: string;
  icon?: string;
  badge?: string;
  tag?: string;
  url?: string;
  requireInteraction?: boolean;
  data?: Record<string, unknown>;
  notification?: PushNotificationData; // FCM-like nested format
}

self.addEventListener('push', (event) => {
  const rawText = event.data?.text() || '';
  const timestamp = new Date().toISOString();
  
  console.log('[SW] Push received at:', timestamp, 'raw:', rawText.substring(0, 200));
  
  // Store raw payload for diagnostics (keep last 5)
  try {
    const diagnostics = JSON.parse(self.indexedDB ? '[]' : '[]');
    // Use postMessage to store in main thread since SW can't access localStorage directly
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then(clients => {
      clients.forEach(client => {
        client.postMessage({
          type: 'PUSH_RAW_PAYLOAD',
          payload: rawText,
          receivedAt: timestamp,
        });
      });
    });
  } catch (e) {
    console.warn('[SW] Failed to store diagnostic:', e);
  }
  
  const defaultData: PushNotificationData = {
    title: "O'KEY ENGLISH",
    body: 'Новое уведомление',
    icon: '/pwa-192x192.png',
    badge: '/pwa-192x192.png',
    tag: 'default',
    data: {}
  };

  let data: PushNotificationData = { ...defaultData };

  try {
    if (event.data) {
      const payload = event.data.json() as PushNotificationData;
      console.log('[SW] Parsed payload:', JSON.stringify(payload).substring(0, 200));
      
      // Support both flat format and nested notification format (FCM-like)
      if (payload.notification && typeof payload.notification === 'object') {
        const notif = payload.notification as PushNotificationData;
        data = { ...defaultData, ...notif, data: payload.data || notif.data };
      } else {
        data = { ...defaultData, ...payload };
      }
    }
  } catch (e) {
    console.error('[SW] Error parsing push data:', e, 'raw:', rawText);
    // Try as text
    if (event.data) {
      data.body = event.data.text();
    }
  }

  // Extended notification options for Service Worker (includes vibrate which is not in standard NotificationOptions)
  interface ExtendedNotificationOptions extends NotificationOptions {
    vibrate?: number[];
    actions?: Array<{ action: string; title: string; icon?: string }>;
  }

  const options: ExtendedNotificationOptions = {
    body: data.body,
    icon: data.icon || '/pwa-192x192.png',
    badge: data.badge || '/pwa-192x192.png',
    tag: data.tag || 'okey-notification',
    vibrate: [100, 50, 100],
    data: {
      ...data.data,
      url: data.url || data.data?.url || '/',
      dateOfArrival: Date.now(),
    },
    actions: [
      { action: 'open', title: 'Открыть' },
      { action: 'close', title: 'Закрыть' }
    ],
    requireInteraction: data.requireInteraction || false,
  };

  const broadcastToClients = async () => {
    try {
      const clientList = await self.clients.matchAll({ type: 'window', includeUncontrolled: true });
      for (const client of clientList) {
        client.postMessage({
          type: 'PUSH_RECEIVED',
          payload: {
            title: data.title,
            body: data.body,
            tag: data.tag,
            url: (options.data as Record<string, unknown> | undefined)?.url,
          },
          receivedAt: Date.now(),
        });
      }
    } catch (e) {
      console.warn('[SW] Failed to broadcast push to clients:', e);
    }
  };

  event.waitUntil(
    Promise.all([
      self.registration.showNotification(data.title, options),
      broadcastToClients(),
    ])
  );
});

// ============= NOTIFICATION CLICK =============
// Types for notification data
interface NotificationPayloadData {
  url?: string;
  [key: string]: unknown;
}

self.addEventListener('notificationclick', (event) => {
  console.log('[SW] Notification clicked:', event.action);
  
  event.notification.close();

  if (event.action === 'close') {
    return;
  }

  const notificationData = event.notification.data as NotificationPayloadData | undefined;
  const urlToOpen = notificationData?.url || '/';

  if (event.action === 'close') {
    return;
  }

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      // Check if there's already a window open
      for (const client of clientList) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          client.focus();
          if (urlToOpen !== '/') {
            (client as WindowClient).navigate(urlToOpen);
          }
          return;
        }
      }
      // Open new window
      return self.clients.openWindow(urlToOpen);
    })
  );
});

// ============= NOTIFICATION CLOSE =============
self.addEventListener('notificationclose', () => {
  console.log('[SW] Notification closed');
});

// ============= MESSAGE HANDLER =============
self.addEventListener('message', (event) => {
  console.log('[SW] Message received:', event.data);
  
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// ============= ACTIVATE =============
self.addEventListener('activate', (event) => {
  console.log('[SW] Activating service worker with push support');
  event.waitUntil(self.clients.claim());
});
