-- Добавляем уроки для Unit 6: My Numbers
INSERT INTO lessons (unit_id, lesson_number, title, objectives, lesson_structure, homework, materials) VALUES
((SELECT id FROM course_units WHERE unit_number = 6 AND course_id = (SELECT id FROM courses WHERE slug = 'super-safari-1')), 1, 'Numbers 1-5 introduction', 'числа 1-5; произношение и распознавание', '0–5: ДЗ-чек/повтор игрушки. 5–15: Разминка — counting toys from previous unit. 15–35: Презентация — numbers 1-5 with finger counting. 35–55: Практика — number recognition; clap the number. 55–60: Number song + ДЗ', 'AB p.19; практиковать счет 1-5', 'PB p.18; AB p.19; Number flashcards; Audio'),
((SELECT id FROM course_units WHERE unit_number = 6 AND course_id = (SELECT id FROM courses WHERE slug = 'super-safari-1')), 2, 'Number recognition activities', 'распознавание чисел; соединение количества с цифрой', '0–5: ДЗ-чек (счет 1-5). 5–15: Разминка — number song with actions. 15–30: Презентация — match quantity to numeral. 30–50: Практика — number bingo; count and circle. 50–60: Number hunt + объяснение ДЗ', 'AB p.20; найти числа дома', 'PB p.19; AB p.20; Bingo sheets'),
((SELECT id FROM course_units WHERE unit_number = 6 AND course_id = (SELECT id FROM courses WHERE slug = 'super-safari-1')), 3, 'Counting objects', 'счет предметов в классе; практическое применение', '0–5: ДЗ-чек (числа дома). 5–15: Разминка — number recognition game. 15–35: Презентация — counting classroom objects. 35–55: Практика — counting stations; how many pencils? 55–60: Counting challenge + ДЗ', 'AB p.21; сосчитать предметы дома', 'PB p.20; AB p.21; Classroom objects'),
((SELECT id FROM course_units WHERE unit_number = 6 AND course_id = (SELECT id FROM courses WHERE slug = 'super-safari-1')), 4, 'Numbers and movements', 'числа с движениями; активные игры со счетом', '0–5: ДЗ-чек (счет дома). 5–15: Разминка — counting objects review. 15–30: Презентация — action counting: 3 jumps, 4 claps. 30–50: Практика — follow number commands; number dance. 50–60: Musical numbers + ДЗ', 'AB p.22; танцевать с числами', 'PB p.21; AB p.22; Music for dancing'),
((SELECT id FROM course_units WHERE unit_number = 6 AND course_id = (SELECT id FROM courses WHERE slug = 'super-safari-1')), 5, 'Number patterns', 'паттерны с числами; последовательности 1-2-3', '0–5: ДЗ-чек (number dance дома). 5–15: Разминка — number movements review. 15–30: Презентация — simple patterns 1-2-1-2. 30–50: Практика — complete the pattern; create patterns. 50–60: Pattern game + объяснение ДЗ', 'AB p.23; найти паттерны дома', 'PB p.22; AB p.23; Pattern materials'),
((SELECT id FROM course_units WHERE unit_number = 6 AND course_id = (SELECT id FROM courses WHERE slug = 'super-safari-1')), 6, 'Number celebration', 'итоговое повторение чисел; число дня рождения', '0–5: ДЗ-чек (паттерны). 5–20: Number games festival — станции с разными играми. 20–40: Birthday numbers — How old are you? 40–55: Number certificates вручение. 55–60: Подготовка к pets unit', 'Повторить числа 1-5; узнать про домашних животных', 'Games stations; Certificates; Birthday props');

-- Добавляем уроки для Unit 7: My Pets
INSERT INTO lessons (unit_id, lesson_number, title, objectives, lesson_structure, homework, materials) VALUES
((SELECT id FROM course_units WHERE unit_number = 7 AND course_id = (SELECT id FROM courses WHERE slug = 'super-safari-1')), 1, 'Leo pets introduction', 'домашние животные Leo; cat, dog, fish', '0–5: ДЗ-чек/повтор числа. 5–15: Разминка — counting 1-5; Do you have pets? 15–35: Презентация — Leo pets: cat, dog, fish. 35–55: Практика — pet sounds; animal movements TPR. 55–60: Pet song + ДЗ', 'AB p.24; выучить названия pets', 'PB p.23; AB p.24; Pet pictures; Audio'),
((SELECT id FROM course_units WHERE unit_number = 7 AND course_id = (SELECT id FROM courses WHERE slug = 'super-safari-1')), 2, 'More pets vocabulary', 'расширение словаря: bird, rabbit, hamster', '0–5: ДЗ-чек (pet names). 5–15: Разминка — pet song with actions. 15–30: Презентация — new pets: bird, rabbit, hamster. 30–50: Практика — pet matching; guess the pet sound. 50–60: Pet memory game + ДЗ', 'AB p.25; нарисовать любимое животное', 'PB p.24; AB p.25; Pet sound audio'),
((SELECT id FROM course_units WHERE unit_number = 7 AND course_id = (SELECT id FROM courses WHERE slug = 'super-safari-1')), 3, 'Pet care', 'уход за животными; feed, walk, love', '0–5: ДЗ-чек (рисунки животных). 5–15: Show and tell — my favorite animal. 15–35: Презентация — caring for pets; feed the cat, walk the dog. 35–55: Практика — pet care role play; responsible pet owner. 55–60: Care song + ДЗ', 'AB p.26; помочь с домашним животным', 'PB p.25; AB p.26; Pet care props'),
((SELECT id FROM course_units WHERE unit_number = 7 AND course_id = (SELECT id FROM courses WHERE slug = 'super-safari-1')), 4, 'Pet colors and sizes', 'описание животных: big dog, small cat, brown rabbit', '0–5: ДЗ-чек (помощь с pets). 5–15: Разминка — pet care song. 15–30: Презентация — describing pets with colors/sizes. 30–50: Практика — describe and guess; colorful pets matching. 50–60: Description game + ДЗ', 'AB p.27; описать домашних животных', 'PB p.26; AB p.27; Colored pet pictures'),
((SELECT id FROM course_units WHERE unit_number = 7 AND course_id = (SELECT id FROM courses WHERE slug = 'super-safari-1')), 5, 'Pet families', 'семьи животных: baby animals, mummy cat, daddy dog', '0–5: ДЗ-чек (описания pets). 5–15: Разминка — pet descriptions review. 15–30: Презентация — animal families; puppy, kitten, chick. 30–50: Практика — match babies to parents; animal family song. 50–60: Family pets craft + ДЗ', 'AB p.28; сделать pet family tree', 'PB p.27; AB p.28; Craft materials'),
((SELECT id FROM course_units WHERE unit_number = 7 AND course_id = (SELECT id FROM courses WHERE slug = 'super-safari-1')), 6, 'Pet show', 'выставка домашних животных; презентации и итоги', '0–5: Подготовка pet show. 5–25: Pet show presentations — дети представляют своих pets. 25–45: Pet talent show — animal movements and sounds. 45–60: Pet awards ceremony + стикеры; переход к food unit', 'Повторить всех pets; подготовиться к еде', 'Award certificates; Pet show setup; Stickers');