-- Добавляем уроки для Unit 8: My Food
INSERT INTO lessons (unit_id, lesson_number, title, objectives, lesson_structure, homework, materials) VALUES
((SELECT id FROM course_units WHERE unit_number = 8 AND course_id = (SELECT id FROM courses WHERE slug = 'super-safari-1')), 1, 'Favorite foods introduction', 'любимая еда Leo; apple, banana, cake', '0–5: ДЗ-чек/повтор pets. 5–15: Разминка — pet sounds review; What do you like to eat? 15–35: Презентация — Leo favorite foods: apple, banana, cake. 35–55: Практика — taste and name; food matching game. 55–60: Yummy song + ДЗ', 'AB p.29; выучить названия еды', 'PB p.28; AB p.29; Food pictures; Audio'),
((SELECT id FROM course_units WHERE unit_number = 8 AND course_id = (SELECT id FROM courses WHERE slug = 'super-safari-1')), 2, 'Healthy foods', 'здоровая еда; vegetables, fruits', '0–5: ДЗ-чек (food names). 5–15: Разминка — yummy song with actions. 15–30: Презентация — healthy foods; carrots, oranges. 30–50: Практика — healthy/unhealthy sorting; try new foods. 50–60: Healthy food song + ДЗ', 'AB p.30; попробовать новый фрукт', 'PB p.29; AB p.30; Real fruits/vegetables'),
((SELECT id FROM course_units WHERE unit_number = 8 AND course_id = (SELECT id FROM courses WHERE slug = 'super-safari-1')), 3, 'Food colors', 'цвета еды; red apple, yellow banana, green vegetables', '0–5: ДЗ-чек (новые фрукты). 5–15: Разминка — healthy food song. 15–35: Презентация — colorful foods; What color is the apple? 35–55: Практика — color food bingo; rainbow foods. 55–60: Color food craft + ДЗ', 'AB p.31; найти разноцветную еду', 'PB p.30; AB p.31; Colored food items'),
((SELECT id FROM course_units WHERE unit_number = 8 AND course_id = (SELECT id FROM courses WHERE slug = 'super-safari-1')), 4, 'Sharing meals', 'совместная еда; sharing lunch, family dinner', '0–5: ДЗ-чек (colorful food). 5–15: Разминка — color food review. 15–30: Презентация — eating together; sharing is caring with food. 30–50: Практика — pretend picnic; share and care role play. 50–60: Sharing meal song + ДЗ', 'AB p.32; поделиться едой с семьей', 'PB p.31; AB p.32; Picnic setup'),
((SELECT id FROM course_units WHERE unit_number = 8 AND course_id = (SELECT id FROM courses WHERE slug = 'super-safari-1')), 5, 'Food counting', 'счет еды; numbers with food items', '0–5: ДЗ-чек (sharing meals). 5–15: Разминка — sharing meal song. 15–30: Презентация — counting food; 3 apples, 5 bananas. 30–50: Практика — food counting activities; How many cookies? 50–60: Counting food game + ДЗ', 'AB p.33; сосчитать еду дома', 'PB p.32; AB p.33; Food counting materials'),
((SELECT id FROM course_units WHERE unit_number = 8 AND course_id = (SELECT id FROM courses WHERE slug = 'super-safari-1')), 6, 'Cooking together', 'простая готовка; following simple recipes', '0–5: ДЗ-чек (food counting). 5–20: Простая готовка — fruit salad making. 20–40: Eating together — наш fruit salad. 40–55: Recipe book создание простых рецептов. 55–60: Cooking certificates + переход к clothes', 'Повторить food words; принести любимую одежду', 'Cooking ingredients; Recipe cards; Certificates');

-- Добавляем уроки для Unit 9: My Clothes
INSERT INTO lessons (unit_id, lesson_number, title, objectives, lesson_structure, homework, materials) VALUES
((SELECT id FROM course_units WHERE unit_number = 9 AND course_id = (SELECT id FROM courses WHERE slug = 'super-safari-1')), 1, 'Leo clothes introduction', 'одежда Leo; hat, shoes, shirt', '0–5: ДЗ-чек/повтор food + любимая одежда детей. 5–15: Разминка — food review; What are you wearing? 15–35: Презентация — Leo clothes: hat, shoes, shirt. 35–55: Практика — clothes matching; dress up Leo game. 55–60: Clothes song + ДЗ', 'AB p.34; выучить названия одежды', 'PB p.33; AB p.34; Clothes flashcards; Audio'),
((SELECT id FROM course_units WHERE unit_number = 9 AND course_id = (SELECT id FROM courses WHERE slug = 'super-safari-1')), 2, 'More clothes vocabulary', 'расширение словаря: dress, trousers, socks', '0–5: ДЗ-чек (clothes names). 5–15: Разминка — clothes song with actions. 15–30: Презентация — new clothes: dress, trousers, socks. 30–50: Практика — clothes memory game; what am I wearing? 50–60: Dress up relay + ДЗ', 'AB p.35; нарисовать свою одежду', 'PB p.34; AB p.35; Dress up clothes'),
((SELECT id FROM course_units WHERE unit_number = 9 AND course_id = (SELECT id FROM courses WHERE slug = 'super-safari-1')), 3, 'Weather and clothes', 'одежда для разной погоды; sunny-hat, rainy-coat', '0–5: ДЗ-чек (рисунки одежды). 5–15: Show and tell — my clothes pictures. 15–35: Презентация — weather and appropriate clothes. 35–55: Практика — weather dress up; what to wear when? 55–60: Weather clothes song + ДЗ', 'AB p.36; выбрать одежду по погоде', 'PB p.35; AB p.36; Weather pictures'),
((SELECT id FROM course_units WHERE unit_number = 9 AND course_id = (SELECT id FROM courses WHERE slug = 'super-safari-1')), 4, 'Clothes colors', 'цвета одежды; my red hat, blue shoes', '0–5: ДЗ-чек (weather clothes). 5–15: Разминка — weather clothes song. 15–30: Презентация — colorful clothes; describe what you wear. 30–50: Практика — color clothes bingo; fashion show prep. 50–60: Color coordination game + ДЗ', 'AB p.37; подготовить fashion show outfit', 'PB p.36; AB p.37; Colorful clothes items'),
((SELECT id FROM course_units WHERE unit_number = 9 AND course_id = (SELECT id FROM courses WHERE slug = 'super-safari-1')), 5, 'Getting dressed', 'процесс одевания; put on, take off', '0–5: ДЗ-чек (fashion outfits). 5–15: Разминка — describe your outfit. 15–30: Презентация — getting dressed sequence; put on shoes first. 30–50: Практика — dressing race; help teddy get dressed. 50–60: Getting ready song + ДЗ', 'AB p.38; помочь дома с одеванием', 'PB p.37; AB p.38; Teddy bear and clothes'),
((SELECT id FROM course_units WHERE unit_number = 9 AND course_id = (SELECT id FROM courses WHERE slug = 'super-safari-1')), 6, 'Fashion show finale', 'показ мод; презентация стилей и итоги', '0–5: Подготовка fashion show. 5–25: Children fashion show — каждый представляет свой outfit. 25–45: Voting for best styles; fashion awards. 45–60: Fashion certificates + стикеры; подготовка к final unit', 'Повторить все clothes; подготовиться к park', 'Fashion show runway; Awards; Certificates');